name: My first workflow
on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome
              run: echo "my first github repository"

            - name: Actions
              uses: actions/checkout@v5.0.0

            - name: List
              run: ls

            - name: Read file
              run: cat Readme.md